sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

# Don't run bundle install
install: echo "skip bundle install"

branches:
  only:
    - master
    - /^(?i:travis).*$/

services: docker

env:
  matrix:
    - INSTANCE=chef12-centos-6
    - INSTANCE=chef12-centos-7
    - INSTANCE=chef12-fedora-26
    - INSTANCE=chef12-ubuntu-14
    - INSTANCE=chef12-ubuntu-16
    - INSTANCE=chef12-debian-8
    - INSTANCE=chef12-debian-9
    - INSTANCE=chef12-amazon
    - INSTANCE=chef13-centos-6
    - INSTANCE=chef13-centos-7
    - INSTANCE=chef13-fedora-26
    - INSTANCE=chef13-ubuntu-14
    - INSTANCE=chef13-ubuntu-16
    - INSTANCE=chef13-debian-8
    - INSTANCE=chef13-debian-9
    - INSTANCE=chef13-amazon

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version


matrix:
  allow_failures:
    - env: INSTANCE=chef12-centos-6
    - env: INSTANCE=chef12-centos-7
    - env: INSTANCE=chef12-fedora-26
    - env: INSTANCE=chef12-ubuntu-14
    - env: INSTANCE=chef12-ubuntu-16
    - env: INSTANCE=chef12-debian-8
    - env: INSTANCE=chef12-debian-9
    - env: INSTANCE=chef12-amazon
    - env: INSTANCE=chef13-centos-6
    - env: INSTANCE=chef13-centos-7
    - env: INSTANCE=chef13-fedora-26
    - env: INSTANCE=chef13-ubuntu-14
    - env: INSTANCE=chef13-ubuntu-16
    - env: INSTANCE=chef13-debian-8
    - env: INSTANCE=chef13-debian-9
    - env: INSTANCE=chef13-amazon
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
